name: PHP test

on: [push, pull_request]

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        php-version: [7.3, 7.4, 8.0, 8.1, 8.2, 8.3]
        os: [ubuntu-latest]
        es-version: [6.8-SNAPSHOT]

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Use PHP ${{ matrix.php-version }}
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-version }}
        extensions: yaml
      env:
        COMPOSER_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Get composer cache directory
      id: composercache
      run: echo "::set-output name=dir::$(composer config cache-files-dir)"

    - name: Cache dependencies
      uses: actions/cache@v4
      with:
        path: ${{ steps.composercache.outputs.dir }}
        key: ${{ runner.os }}-php-${{ matrix.php-version }}-${{ hashFiles('**/composer.json') }}
        restore-keys: ${{ runner.os }}-php-${{ matrix.php-version }}-
          
    - name: Install dependencies
      if: ${{ matrix.php-version != '8.0' }}
      run: |
        composer install --prefer-dist

    - name: ignore ignore-platform-reqs if it is using php 8
      if: ${{ matrix.php-version == '8.0' }}
      run: |
        composer install --prefer-dist --ignore-platform-reqs

    - name: PHP Coding Standards
      run: |
        composer run-script phpcs

    - name: PHP Static Analysis Tool
      run: |
        composer run-script phpstan

    - name: Unit tests
      run: |
        vendor/bin/phpunit -c phpunit.xml.dist
      env:
        TEST_SUITE: oss
